CREATE TABLE DWADMIN.DI_WORKFLOW_NONCONCURRENCY (
    WORKFLOWKEY                     NUMBER(11) ,    -- CONSTRAINT DI_WORKFLOW_NONCONCURRENCY_N1 NOT NULL,
    NONCONCURRENT_WORKFLOWKEY       NUMBER(11)  ,   -- CONSTRAINT DI_WORKFLOW_NONCONCURRENCY_N2 NOT NULL),
    PROCESS_TIMESTAMP                TIMESTAMP(6)   -- CONSTRAINT DI_WORKFLOW_NONCONCURRENCY_N3 NOT NULL)
)   
 TABLESPACE DWADMIN_DT_TS
NOLOGGING 
NOPARALLEL
/

CREATE UNIQUE INDEX DWADMIN.DI_WORKFLOW_NONCONCURRENCY_PK ON DWADMIN.DI_WORKFLOW_NONCONCURRENCY
(WORKFLOWKEY, NONCONCURRENT_WORKFLOWKEY)
TABLESPACE DWADMIN_IX_TS
NOLOGGING
NOPARALLEL
/

ALTER TABLE DWADMIN.DI_WORKFLOW_NONCONCURRENCY ADD (
  PRIMARY KEY
  (WORKFLOWKEY, NONCONCURRENT_WORKFLOWKEY)
  USING INDEX DWADMIN.DI_WORKFLOW_NONCONCURRENCY_PK
  ENABLE VALIDATE)
/  

ALTER TABLE DWADMIN.DI_WORKFLOW_NONCONCURRENCY ADD (
  CONSTRAINT DI_WORKFLOW_NONCONCURRENCY_R1 
  FOREIGN KEY (WORKFLOWKEY) 
  REFERENCES DWADMIN.DI_WORKFLOW (WORKFLOWKEY)
  ENABLE VALIDATE,
  CONSTRAINT DI_WORKFLOW_NONCONCURRENCY_R2 
  FOREIGN KEY (NONCONCURRENT_WORKFLOWKEY) 
  REFERENCES DWADMIN.DI_WORKFLOW (WORKFLOWKEY)
  ENABLE VALIDATE)
/  