

CREATE TABLE PBOWMAN.RAI_CUSTSUBSET
(
  CUSTOMERKEY       NUMBER(11),
  COLLECTIONKEY     NUMBER(11)                  NOT NULL,
  RESPONSE          VARCHAR2(1 BYTE),
  RESPONSECODE      VARCHAR2(20 BYTE),
  PROCESSORGROUP    VARCHAR2(1 BYTE),
  REQUESTDATE       DATE,
  CARD_TYPE         VARCHAR2(20 BYTE),
  CURRENCYCODE      VARCHAR2(4 BYTE),
  AMOUNT            NUMBER(15,2),
  BILLINGCOUNTRY    VARCHAR2(40 BYTE),
  MARKETINGREGION   VARCHAR2(40 BYTE),
  EXCLUSION_REASON  VARCHAR2(9 BYTE)
)
TABLESPACE USERS_NEW
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



CREATE TABLE PBOWMAN.RA_CGROUPCOUNTS
(
  CUSTOMERKEY               NUMBER(11),
  COLLECTIONGROUP           NUMBER,
  COLLECTIONGROUPSTARTDATE  DATE,
  COLLECTIONGROUPKEY        NUMBER(11)          NOT NULL,
  NEXTGROUPKEY              NUMBER,
  NEXTGROUPSTARTDATE        DATE,
  ATTEMPTSINGROUP           NUMBER,
  FINALATTEMPT              NUMBER
)
TABLESPACE USERS_NEW
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
