DROP TABLE ODS_CENTRAL.GT_RAD_NEWATTEMPTS_EX1 CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE ODS_CENTRAL.GT_RAD_NEWATTEMPTS_EX1
(
  CUSTOMERKEY       NUMBER(11),
  COLLECTIONKEY     NUMBER(11)                  NOT NULL,
  RESPONSE          VARCHAR2(1 CHAR),
  RESPONSECODE      VARCHAR2(20 CHAR),
  PROCESSORGROUP    VARCHAR2(1 CHAR),
  REQUESTDATE       DATE,
  CARD_TYPE         VARCHAR2(20 CHAR),
  CURRENCYCODE      VARCHAR2(4 CHAR),
  AMOUNT            NUMBER(15,2),
  BILLINGCOUNTRY    VARCHAR2(40 CHAR),
  MARKETINGREGION   VARCHAR2(40 CHAR),
  RETRY_COUNT       NUMBER(11),
  EXCLUSION_REASON  VARCHAR2(9 CHAR),
  NEW_GROUP_FLAG    NUMBER(11),
  COLLECTED_FLAG    NUMBER(11)
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE UNIQUE INDEX ODS_CENTRAL.RAD_GTNEWEX1_IX ON ODS_CENTRAL.GT_RAD_NEWATTEMPTS_EX1
(COLLECTIONKEY);

DROP TABLE ODS_CENTRAL.GT_RAD_ATTEMPTGROUPASSOC_EX2 CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE ODS_CENTRAL.GT_RAD_ATTEMPTGROUPASSOC_EX2
(
  CUSTOMERKEY         NUMBER(11),
  COLLECTIONKEY       NUMBER(11),
  COLLECTIONGROUPKEY  NUMBER(11)
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE UNIQUE INDEX ODS_CENTRAL.RAD_AGROUPEX2_IX ON ODS_CENTRAL.GT_RAD_ATTEMPTGROUPASSOC_EX2
(COLLECTIONKEY);

DROP TABLE ODS_CENTRAL.GT_RAD_COLL_GROUP_DISP_CF1 CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE ODS_CENTRAL.GT_RAD_COLL_GROUP_DISP_CF1
(
  CUSTOMERKEY               NUMBER(11),
  COLLECTIONGROUP           NUMBER,
  COLLECTIONGROUPSTARTDATE  DATE,
  COLLECTIONGROUPKEY        NUMBER(11)          NOT NULL,
  NEXTGROUPKEY              NUMBER,
  NEXTGROUPSTARTDATE        DATE,
  ATTEMPTSINGROUP           NUMBER,
  FINALATTEMPT              NUMBER,
  DAYSTOCOLLECT             NUMBER,
  DECLINESUNTILSUCCESSFUL   NUMBER,
  GROUP_DISPOSITION         VARCHAR2(100 CHAR),
  GROUP_DISPOSITION_DETAIL  VARCHAR2(200 CHAR),
  FINAL_STATUS_FLAG         NUMBER,
  PROCESS_DATETIME          DATE
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;

DROP TABLE ODS_CENTRAL.GT_RAD_DISPATTEMPTS_EX2 CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE ODS_CENTRAL.GT_RAD_DISPATTEMPTS_EX2
(
  COLLECTIONKEY     NUMBER(11)                  NOT NULL,
  CUSTOMERKEY       NUMBER(11),
  RESPONSE          VARCHAR2(1 BYTE),
  PROCESSORGROUP    VARCHAR2(1 BYTE),
  RETRYCOUNT        NUMBER(5),
  REQUESTDATE       DATE,
  AMOUNT            NUMBER(15,2),
  ODS_CURRENT_FLAG  NUMBER(1)                   NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;

DROP TABLE ODS_CENTRAL.GT_RAD_NEW_COLL_GROUPS_EX1 CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE ODS_CENTRAL.GT_RAD_NEW_COLL_GROUPS_EX1
(
  CUSTOMERKEY               NUMBER(11),
  COLLECTIONGROUP           NUMBER(11),
  COLLECTIONGROUPSTARTDATE  DATE,
  COLLECTIONGROUPKEY        NUMBER(11)          NOT NULL,
  NEXTGROUPKEY              NUMBER(11),
  NEXTGROUPSTARTDATE        DATE
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;

DROP TABLE ODS_CENTRAL.GT_RAD_NEW_COLL_GROUPS_EX3 CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE ODS_CENTRAL.GT_RAD_NEW_COLL_GROUPS_EX3
(
  CUSTOMERKEY          NUMBER(11),
  PREVCOLLECTIONGROUP  NUMBER
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;

DROP TABLE ODS_CENTRAL.GT_RAD_NEW_COLLECTION_GROUPS CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE ODS_CENTRAL.GT_RAD_NEW_COLLECTION_GROUPS
(
  CUSTOMERKEY               NUMBER(11),
  COLLECTIONGROUP           NUMBER(11),
  COLLECTIONGROUPSTARTDATE  DATE,
  COLLECTIONGROUPKEY        NUMBER(11)          NOT NULL
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;

DROP TABLE ODS_CENTRAL.GT_RAD_NEW_GROUP_STATS CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE ODS_CENTRAL.GT_RAD_NEW_GROUP_STATS
(
  CUSTOMERKEY               NUMBER(11),
  COLLECTIONGROUP           NUMBER(11),
  COLLECTIONGROUPSTARTDATE  DATE,
  COLLECTIONGROUPKEY        NUMBER(11)          NOT NULL,
  NEXTGROUPKEY              NUMBER(11),
  NEXTGROUPSTARTDATE        DATE,
  NEWATTEMPTS               NUMBER,
  MOSTRECENTATTEMPT         NUMBER,
  COLLECTED_FLAG            NUMBER(11),
  NEW_GROUP_FLAG            NUMBER(11)
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


DROP TABLE ODS_CENTRAL.GT_RAD_NEWATTEMPTS_EX1 CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE ODS_CENTRAL.GT_RAD_NEWATTEMPTS_EX1
(
  CUSTOMERKEY       NUMBER(11),
  COLLECTIONKEY     NUMBER(11)                  NOT NULL,
  RESPONSE          VARCHAR2(1 CHAR),
  RESPONSECODE      VARCHAR2(20 CHAR),
  PROCESSORGROUP    VARCHAR2(1 CHAR),
  REQUESTDATE       DATE,
  CARD_TYPE         VARCHAR2(20 CHAR),
  CURRENCYCODE      VARCHAR2(4 CHAR),
  AMOUNT            NUMBER(15,2),
  BILLINGCOUNTRY    VARCHAR2(40 CHAR),
  MARKETINGREGION   VARCHAR2(40 CHAR),
  RETRY_COUNT       NUMBER(11),
  EXCLUSION_REASON  VARCHAR2(9 CHAR),
  NEW_GROUP_FLAG    NUMBER(11),
  COLLECTED_FLAG    NUMBER(11)
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE UNIQUE INDEX ODS_CENTRAL.RAD_GTNEWEX1_IX ON ODS_CENTRAL.GT_RAD_NEWATTEMPTS_EX1
(COLLECTIONKEY);

DROP TABLE ODS_CENTRAL.GT_RAD_NEWATTEMPTS_STATS_EX3 CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE ODS_CENTRAL.GT_RAD_NEWATTEMPTS_STATS_EX3
(
  COLLECTIONGROUPKEY  NUMBER(11),
  NEWATTEMPTS         NUMBER,
  MOSTRECENTATTEMPT   NUMBER
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE UNIQUE INDEX ODS_CENTRAL.RAD_ASTATSEX3_IX ON ODS_CENTRAL.GT_RAD_NEWATTEMPTS_STATS_EX3
(COLLECTIONGROUPKEY);
