--Looks like this is working so far executed as a item not a script (so not keeping Toad locked up) but will have to see.
DECLARE CHECK_CONSTRAINT_VIOLATED EXCEPTION;  PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);
begin ods_central.ods_retryanalysis('07-AUG-2014','08-AUG-2014');EXCEPTION
  WHEN CHECK_CONSTRAINT_VIOLATED THEN  -- catch the ORA-02290 exception
    DBMS_OUTPUT.PUT_LINE('Failed due to check constraint violation');  end;
DECLARE CHECK_CONSTRAINT_VIOLATED EXCEPTION;  PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);
begin ods_central.ods_retryanalysis('08-AUG-2014','09-AUG-2014');EXCEPTION
  WHEN CHECK_CONSTRAINT_VIOLATED THEN  -- catch the ORA-02290 exception
    DBMS_OUTPUT.PUT_LINE('Failed due to check constraint violation');  end;
DECLARE CHECK_CONSTRAINT_VIOLATED EXCEPTION;  PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);
begin ods_central.ods_retryanalysis('09-AUG-2014','10-AUG-2014');EXCEPTION
  WHEN CHECK_CONSTRAINT_VIOLATED THEN  -- catch the ORA-02290 exception
    DBMS_OUTPUT.PUT_LINE('Failed due to check constraint violation');  end;
DECLARE CHECK_CONSTRAINT_VIOLATED EXCEPTION;  PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);
begin ods_central.ods_retryanalysis('10-AUG-2014','11-AUG-2014');EXCEPTION
  WHEN CHECK_CONSTRAINT_VIOLATED THEN  -- catch the ORA-02290 exception
    DBMS_OUTPUT.PUT_LINE('Failed due to check constraint violation');  end;
DECLARE CHECK_CONSTRAINT_VIOLATED EXCEPTION;  PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);
begin ods_central.ods_retryanalysis('11-AUG-2014','12-AUG-2014');EXCEPTION
  WHEN CHECK_CONSTRAINT_VIOLATED THEN  -- catch the ORA-02290 exception
    DBMS_OUTPUT.PUT_LINE('Failed due to check constraint violation');  end;
DECLARE CHECK_CONSTRAINT_VIOLATED EXCEPTION;  PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);
begin ods_central.ods_retryanalysis('12-AUG-2014','13-AUG-2014');EXCEPTION
  WHEN CHECK_CONSTRAINT_VIOLATED THEN  -- catch the ORA-02290 exception
    DBMS_OUTPUT.PUT_LINE('Failed due to check constraint violation');  end;
DECLARE CHECK_CONSTRAINT_VIOLATED EXCEPTION;  PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);
begin ods_central.ods_retryanalysis('13-AUG-2014','14-AUG-2014');EXCEPTION
  WHEN CHECK_CONSTRAINT_VIOLATED THEN  -- catch the ORA-02290 exception
    DBMS_OUTPUT.PUT_LINE('Failed due to check constraint violation');  end;
DECLARE CHECK_CONSTRAINT_VIOLATED EXCEPTION;  PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);
begin ods_central.ods_retryanalysis('14-AUG-2014','15-AUG-2014');EXCEPTION
  WHEN CHECK_CONSTRAINT_VIOLATED THEN  -- catch the ORA-02290 exception
    DBMS_OUTPUT.PUT_LINE('Failed due to check constraint violation');  end;
DECLARE CHECK_CONSTRAINT_VIOLATED EXCEPTION;  PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);
begin ods_central.ods_retryanalysis('15-AUG-2014','16-AUG-2014');EXCEPTION
  WHEN CHECK_CONSTRAINT_VIOLATED THEN  -- catch the ORA-02290 exception
    DBMS_OUTPUT.PUT_LINE('Failed due to check constraint violation');  end;
DECLARE CHECK_CONSTRAINT_VIOLATED EXCEPTION;  PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);
begin ods_central.ods_retryanalysis('16-AUG-2014','17-AUG-2014');EXCEPTION
  WHEN CHECK_CONSTRAINT_VIOLATED THEN  -- catch the ORA-02290 exception
    DBMS_OUTPUT.PUT_LINE('Failed due to check constraint violation');  end;
DECLARE CHECK_CONSTRAINT_VIOLATED EXCEPTION;  PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);
begin ods_central.ods_retryanalysis('17-AUG-2014','18-AUG-2014');EXCEPTION
  WHEN CHECK_CONSTRAINT_VIOLATED THEN  -- catch the ORA-02290 exception
    DBMS_OUTPUT.PUT_LINE('Failed due to check constraint violation');  end;
DECLARE CHECK_CONSTRAINT_VIOLATED EXCEPTION;  PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);
begin ods_central.ods_retryanalysis('18-AUG-2014','19-AUG-2014');EXCEPTION
  WHEN CHECK_CONSTRAINT_VIOLATED THEN  -- catch the ORA-02290 exception
    DBMS_OUTPUT.PUT_LINE('Failed due to check constraint violation');  end;
DECLARE CHECK_CONSTRAINT_VIOLATED EXCEPTION;  PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);
begin ods_central.ods_retryanalysis('19-AUG-2014','20-AUG-2014');EXCEPTION
  WHEN CHECK_CONSTRAINT_VIOLATED THEN  -- catch the ORA-02290 exception
    DBMS_OUTPUT.PUT_LINE('Failed due to check constraint violation');  end;
DECLARE CHECK_CONSTRAINT_VIOLATED EXCEPTION;  PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);
begin ods_central.ods_retryanalysis('20-AUG-2014','21-AUG-2014');EXCEPTION
  WHEN CHECK_CONSTRAINT_VIOLATED THEN  -- catch the ORA-02290 exception
    DBMS_OUTPUT.PUT_LINE('Failed due to check constraint violation');  end;
DECLARE CHECK_CONSTRAINT_VIOLATED EXCEPTION;  PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);
begin ods_central.ods_retryanalysis('21-AUG-2014','22-AUG-2014');EXCEPTION
  WHEN CHECK_CONSTRAINT_VIOLATED THEN  -- catch the ORA-02290 exception
    DBMS_OUTPUT.PUT_LINE('Failed due to check constraint violation');  end;
DECLARE CHECK_CONSTRAINT_VIOLATED EXCEPTION;  PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);
begin ods_central.ods_retryanalysis('22-AUG-2014','23-AUG-2014');EXCEPTION
  WHEN CHECK_CONSTRAINT_VIOLATED THEN  -- catch the ORA-02290 exception
    DBMS_OUTPUT.PUT_LINE('Failed due to check constraint violation');  end;
DECLARE CHECK_CONSTRAINT_VIOLATED EXCEPTION;  PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);
begin ods_central.ods_retryanalysis('23-AUG-2014','24-AUG-2014');EXCEPTION
  WHEN CHECK_CONSTRAINT_VIOLATED THEN  -- catch the ORA-02290 exception
    DBMS_OUTPUT.PUT_LINE('Failed due to check constraint violation');  end;
DECLARE CHECK_CONSTRAINT_VIOLATED EXCEPTION;  PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);
begin ods_central.ods_retryanalysis('24-AUG-2014','25-AUG-2014');EXCEPTION
  WHEN CHECK_CONSTRAINT_VIOLATED THEN  -- catch the ORA-02290 exception
    DBMS_OUTPUT.PUT_LINE('Failed due to check constraint violation');  end;
DECLARE CHECK_CONSTRAINT_VIOLATED EXCEPTION;  PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);
begin ods_central.ods_retryanalysis('25-AUG-2014','26-AUG-2014');EXCEPTION
  WHEN CHECK_CONSTRAINT_VIOLATED THEN  -- catch the ORA-02290 exception
    DBMS_OUTPUT.PUT_LINE('Failed due to check constraint violation');  end;
DECLARE CHECK_CONSTRAINT_VIOLATED EXCEPTION;  PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);
begin ods_central.ods_retryanalysis('26-AUG-2014','27-AUG-2014');EXCEPTION
  WHEN CHECK_CONSTRAINT_VIOLATED THEN  -- catch the ORA-02290 exception
    DBMS_OUTPUT.PUT_LINE('Failed due to check constraint violation');  end;
DECLARE CHECK_CONSTRAINT_VIOLATED EXCEPTION;  PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);
begin ods_central.ods_retryanalysis('27-AUG-2014','28-AUG-2014');EXCEPTION
  WHEN CHECK_CONSTRAINT_VIOLATED THEN  -- catch the ORA-02290 exception
    DBMS_OUTPUT.PUT_LINE('Failed due to check constraint violation');  end;
DECLARE CHECK_CONSTRAINT_VIOLATED EXCEPTION;  PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);
begin ods_central.ods_retryanalysis('28-AUG-2014','29-AUG-2014');EXCEPTION
  WHEN CHECK_CONSTRAINT_VIOLATED THEN  -- catch the ORA-02290 exception
    DBMS_OUTPUT.PUT_LINE('Failed due to check constraint violation');  end;
DECLARE CHECK_CONSTRAINT_VIOLATED EXCEPTION;  PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);
begin ods_central.ods_retryanalysis('29-AUG-2014','30-AUG-2014');EXCEPTION
  WHEN CHECK_CONSTRAINT_VIOLATED THEN  -- catch the ORA-02290 exception
    DBMS_OUTPUT.PUT_LINE('Failed due to check constraint violation');  end;
DECLARE CHECK_CONSTRAINT_VIOLATED EXCEPTION;  PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);
begin ods_central.ods_retryanalysis('30-AUG-2014','31-AUG-2014');EXCEPTION
  WHEN CHECK_CONSTRAINT_VIOLATED THEN  -- catch the ORA-02290 exception
    DBMS_OUTPUT.PUT_LINE('Failed due to check constraint violation');  end;
DECLARE CHECK_CONSTRAINT_VIOLATED EXCEPTION;  PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);
begin ods_central.ods_retryanalysis('31-AUG-2014','01-SEP-2014');EXCEPTION
  WHEN CHECK_CONSTRAINT_VIOLATED THEN  -- catch the ORA-02290 exception
    DBMS_OUTPUT.PUT_LINE('Failed due to check constraint violation');  end;